package gradeBookClient.edu.asu.cse564.assign2.crud.gradebook.arao23.cli.ui;
import gradeBookClient.edu.asu.cse564.assign2.crud.gradebook.arao23.cli.util.Converter;
import java.net.URL;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBException;
import com.sun.jersey.api.client.ClientResponse;
import gradeBookClient.edu.asu.cse564.assign2.crud.gradebook.arao23.cli.model.GradeItem;
import javax.ws.rs.core.Response;
import javax.swing.JFrame;
import javax.xml.bind.JAXBException;
import java.net.URI;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class StudentUI extends javax.swing.JFrame {
    private GradeBookClient cliGradeBook;
    private URI resourceURI;
    
     private void errDial(String err) {
        JOptionPane op = new JOptionPane(err, JOptionPane.ERROR_MESSAGE);
        JDialog box = op.createDialog("handle Error");
        box.setAlwaysOnTop(true);
        box.setVisible(true);
    }

    private void startUpScreen() {
        if (ID_STU_TEXT.getText().equals("")) {
            ID_STU_TEXT.setText("0");
        }
        if (FEEDBACK_GOT.getText().equals("")) {
            FEEDBACK_GOT.setText("-");
        }
        if (NAME_GRADEITEM.getText().equals("")) {
            NAME_GRADEITEM.setText("NA");
        }
        if (MARKS_OBTAINED.getText().equals("")) {
            MARKS_OBTAINED.setText("0");
        }
        if (MAX_WEIGHTAGE.getText().equals("")) {
            MAX_WEIGHTAGE.setText("0");
        }
        if (APPEAL_TEXT.getText().equals("")) {
            APPEAL_TEXT.setText("-");
        }
    }
    
    private void fillUpScreen(ClientResponse clientResponse, boolean buttonSel) {
        String ent = clientResponse.getEntity(String.class);
        try {
            if ((clientResponse.getStatus() == Response.Status.OK.getStatusCode()) || (clientResponse.getStatus() == Response.Status.CREATED.getStatusCode())) {
                GradeItem gra = (GradeItem) Converter.convertFromXmlToObject(ent, GradeItem.class);
                //Student ID
                NAME_GRADEITEM.setText(gra.getGradeItemName());
                FEEDBACK_GOT.setText(gra.getFeedback());
                APPEAL_TEXT.setText(gra.getAppeal());
                MARKS_OBTAINED.setText(String.valueOf(gra.getMarksObtained()));
                MAX_WEIGHTAGE.setText(String.valueOf(gra.getPercentageAllocation()));

                if (buttonSel) {
                    errDial("Appeal lodged Successfully !!");
                }
            } else {
                ID_STU_TEXT.setText("");
                NAME_GRADEITEM.setText("");
                FEEDBACK_GOT.setText("");
                MARKS_OBTAINED.setText("");
                MAX_WEIGHTAGE.setText("");
                APPEAL_TEXT.setText("");
                if (buttonSel) {
                    errDial("Appeal lodging Failed !!");
                }
            }
            // Populate HTTP Header Information
            RESPONSE_TEXT.setText(Integer.toString(clientResponse.getStatus()));
            MEDIA_TYPE_TEXT.setText(clientResponse.getType().getType() + "/" + clientResponse.getType().getSubtype());

        } catch (JAXBException e) {
            e.printStackTrace();
        }
    }

    public static boolean checkNumber(String val) {
        try {
            int num = Integer.parseInt(val);
            return true;
        } catch (NumberFormatException exx) {
            return false;
        }
    }

    public StudentUI() {
        initComponents();
        firstButtonClick();
        cliGradeBook = new GradeBookClient();
        FEEDBACK_GOT.disable();
        MARKS_OBTAINED.disable();
        MAX_WEIGHTAGE.disable();
        MEDIA_TYPE_TEXT.disable();
        RESPONSE_TEXT.disable();
    }

    private GradeItem generatePOJO() {

        startUpScreen();
        GradeItem gra = new GradeItem();
        gra.setFeedback(FEEDBACK_GOT.getText());
        gra.setGradeItemName(NAME_GRADEITEM.getText());
        gra.setPercentageAllocation(Integer.parseInt(MAX_WEIGHTAGE.getText()));
        gra.setMarksObtained(Integer.parseInt(MARKS_OBTAINED.getText()));
        gra.setAppeal(APPEAL_TEXT.getText());
        return gra;
    }

    private void firstButtonClick() {

        APPEAL_TEXT.setVisible(true);
        APEAL_TEXT_LABEL.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID_LABEL = new javax.swing.JLabel();
        GRADEITEM_LABEL = new javax.swing.JLabel();
        MAX_WT_LABEL = new javax.swing.JLabel();
        MARKS_OBTAINED_LABEL = new javax.swing.JLabel();
        FEEDBACK_LABEL = new javax.swing.JLabel();
        ID_STU_TEXT = new javax.swing.JTextField();
        NAME_GRADEITEM = new javax.swing.JTextField();
        MAX_WEIGHTAGE = new javax.swing.JTextField();
        MARKS_OBTAINED = new javax.swing.JTextField();
        FEEDBACK_GOT = new javax.swing.JTextField();
        RESPONSE_LABEL = new javax.swing.JLabel();
        MEDIA_TYPE_TEXT = new javax.swing.JTextField();
        RESPONSE_TEXT = new javax.swing.JTextField();
        MEDIA_LABEL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        APEAL_TEXT_LABEL = new javax.swing.JLabel();
        BUTTON1_BACK = new javax.swing.JButton();
        SUBMIT_APPEAL_BUTTON = new javax.swing.JButton();
        MAIN_BUTTON_SUBMIT = new javax.swing.JButton();
        APPEAL_TEXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Know Your Grades");

        ID_LABEL.setText("Student Id");

        GRADEITEM_LABEL.setText("Grade Item Name");

        MAX_WT_LABEL.setText("Weightage (max wt)");

        MARKS_OBTAINED_LABEL.setText("Marks/Grades obtained");

        FEEDBACK_LABEL.setText("Feedback");

        RESPONSE_LABEL.setText("Response Code");

        MEDIA_LABEL.setText("Media Type");

        APEAL_TEXT_LABEL.setText("Write Appeal");

        BUTTON1_BACK.setText("Back");
        BUTTON1_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON1_BACKActionPerformed(evt);
            }
        });

        SUBMIT_APPEAL_BUTTON.setText("Appeal");
        SUBMIT_APPEAL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMIT_APPEAL_BUTTONActionPerformed(evt);
            }
        });

        MAIN_BUTTON_SUBMIT.setText("GetGrades");
        MAIN_BUTTON_SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIN_BUTTON_SUBMITActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Write a appeal request and Click on Appeal if you are not happy with the Grade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MEDIA_TYPE_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MAX_WT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FEEDBACK_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GRADEITEM_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MARKS_OBTAINED_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RESPONSE_LABEL)
                                        .addGap(25, 25, 25)
                                        .addComponent(RESPONSE_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MEDIA_LABEL)))
                                .addGap(241, 241, 241)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ID_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NAME_GRADEITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ID_STU_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MAX_WEIGHTAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MARKS_OBTAINED, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FEEDBACK_GOT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(MAIN_BUTTON_SUBMIT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(BUTTON1_BACK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(APEAL_TEXT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(APPEAL_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SUBMIT_APPEAL_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_STU_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_LABEL))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME_GRADEITEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRADEITEM_LABEL))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAX_WEIGHTAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAX_WT_LABEL))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MARKS_OBTAINED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MARKS_OBTAINED_LABEL))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FEEDBACK_GOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FEEDBACK_LABEL))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RESPONSE_LABEL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RESPONSE_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MEDIA_LABEL)
                        .addComponent(MEDIA_TYPE_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAIN_BUTTON_SUBMIT)
                    .addComponent(BUTTON1_BACK))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APEAL_TEXT_LABEL)
                    .addComponent(APPEAL_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUBMIT_APPEAL_BUTTON))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(685, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON1_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON1_BACKActionPerformed
        MainScreenUI mainUI = new MainScreenUI();
        mainUI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BUTTON1_BACKActionPerformed

    private void MAIN_BUTTON_SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIN_BUTTON_SUBMITActionPerformed
        if ((ID_STU_TEXT.getText().equalsIgnoreCase("")) || (NAME_GRADEITEM.getText().equalsIgnoreCase(""))) {
            errDial("Student Id and Grade Item Name are mandatory ");
            return;
        }
        if (!(checkNumber(ID_STU_TEXT.getText()))) {
            errDial("Student Id should be an Integer ");
            return;
        }
        ClientResponse clientResponse = cliGradeBook.read(ClientResponse.class, ID_STU_TEXT.getText(), NAME_GRADEITEM.getText());
        this.fillUpScreen(clientResponse, false);

    }//GEN-LAST:event_MAIN_BUTTON_SUBMITActionPerformed

    private void SUBMIT_APPEAL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMIT_APPEAL_BUTTONActionPerformed
        if ((ID_STU_TEXT.getText().equalsIgnoreCase("")) || (NAME_GRADEITEM.getText().equalsIgnoreCase(""))) {
            errDial("Student Id and Grade Item Name are mandatory ");
            return;
        }
        if (APPEAL_TEXT.getText().equalsIgnoreCase("")) {
            errDial("Provide details to lodge an appeal");
            return;
        }
        if (!(checkNumber(ID_STU_TEXT.getText()))) {
            errDial("Student Id should be an Integer ");
            return;
        }
        ClientResponse clientResponse = cliGradeBook.updateAppealGradeBookCl(ID_STU_TEXT.getText(), this.generatePOJO());
        resourceURI = clientResponse.getLocation();
        this.fillUpScreen(clientResponse, true);
    }//GEN-LAST:event_SUBMIT_APPEAL_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APEAL_TEXT_LABEL;
    private javax.swing.JTextField APPEAL_TEXT;
    private javax.swing.JButton BUTTON1_BACK;
    private javax.swing.JTextField FEEDBACK_GOT;
    private javax.swing.JLabel FEEDBACK_LABEL;
    private javax.swing.JLabel GRADEITEM_LABEL;
    private javax.swing.JLabel ID_LABEL;
    private javax.swing.JTextField ID_STU_TEXT;
    private javax.swing.JButton MAIN_BUTTON_SUBMIT;
    private javax.swing.JTextField MARKS_OBTAINED;
    private javax.swing.JLabel MARKS_OBTAINED_LABEL;
    private javax.swing.JTextField MAX_WEIGHTAGE;
    private javax.swing.JLabel MAX_WT_LABEL;
    private javax.swing.JLabel MEDIA_LABEL;
    private javax.swing.JTextField MEDIA_TYPE_TEXT;
    private javax.swing.JTextField NAME_GRADEITEM;
    private javax.swing.JLabel RESPONSE_LABEL;
    private javax.swing.JTextField RESPONSE_TEXT;
    private javax.swing.JButton SUBMIT_APPEAL_BUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
